exercicio 1


In [33]:
import numpy as np

# Criar a matriz 50x50 com números inteiros randômicos entre 1 e 100
matriz = np.random.randint(1, 101, size=(50, 50))

# Encontrar as 100 posições centrais (10x10 no centro da matriz)
centro = matriz[20:30, 20:30]

# Mostrar as 100 posições centrais
print("As 100 posições centrais (10x10 no centro da matriz) são:")
print(centro)


As 100 posições centrais (10x10 no centro da matriz) são:
[[  9  41  47  11  18   7  56  56  20  79]
 [  8  26  39  56  31  45  34  52  31  74]
 [ 67  13  45  30  60  50  33   6  23  28]
 [ 85  88  85  99  73  81  61  42   6  29]
 [ 79   7  13  13  85  90   7  49  17  79]
 [ 25  84  42  94  11  29  66  26   5  49]
 [100  78  91  92  89   4  77  13  59  61]
 [ 31  27  21   5  43  47  40  40  30  64]
 [ 43  31  75   8  64   3  93  80  56  94]
 [ 24  82  10  19   7  62  49  75  60  69]]


Exercicio 2


In [6]:
import numpy as np

# Carregar a matriz 50x50 com números inteiros randômicos entre 0 e 100 criada anteriormente
# Se você não tiver a matriz anteriormente criada, certifique-se de gerá-la primeiro
matriz = np.random.randint(0, 101, size=(50, 50))

# Mostrar os múltiplos de 7
print("Múltiplos de 7 na matriz:")
multiplos_de_7 = matriz[matriz % 7 == 0]
print(multiplos_de_7)

# Contar a quantidade de números pares
numeros_pares = matriz[matriz % 2 == 0]
quantidade_pares = len(numeros_pares)
print("Quantidade de números pares na matriz:", quantidade_pares)


Múltiplos de 7 na matriz:
[56 49 98 56 98 56 21 14 49 42 28 14 42 77 14 70 56 77 28 42 56 35 14  0
 63 28 77 49 28 56 84 63 56 14 84  0 28  0 77 42 35 70 77 28  0 63  7 21
  0 35  7 63 77  7 70  7 70 77 42 28 84 49  0  0 42  0 28 35 63 70 98 63
 98 84 84 70 70 21 91 63 70 49 84 49 84 14 84 91 70 14 49 28 49 77 21 56
 91 70 35 91 56 28 35  0 42 63 28 21 56 28 28 21 91 70  7 21 21 49 21 21
 56 63 14 14 14 70 70 14 56 14 63 98 77 91  0 21 70 98 21  7  7 35 35  0
 84 56 63 21 28 35  0 49 35  0 21 63 98 28 84 35  0 21 56  0 21 21  0  0
 21 63 28 21 56  7 63 70  7 70 35 14 49 98  7 56 91 77 84 56 49 49 28  7
 49 70 98  7 49 28 35 14 49 14  0 14 21 98 98 84  0 49 70 42 14  0 21  7
 42 21 35 28 14 35 77 70 84 98 91  7 63 49 21 56 56 98 84 98 98 49 84 42
 56  0 56 91 14 35 14 28  0 70 28 63 21 70 21 98 28 84 84 98  7 21 98 21
 14 42 63 21 42 77 42 21 63 63 84 14  7  0 42  7 49 77 56 84 84 35 63 84
 77 70 35 63  0 91 84 84 28 77 98 14 14  7 70 77 91 98 56 84  7  0 21  0
 49 56 21 63 98 21 98 70 

exercicio 3


In [7]:
import numpy as np

# Carregar a matriz 50x50 com números inteiros randômicos entre 0 e 100 criada anteriormente
# Se você não tiver a matriz anteriormente criada, certifique-se de gerá-la primeiro
matriz = np.random.randint(0, 101, size=(50, 50))

# Criar uma nova matriz contendo as raízes quadradas dos elementos da matriz original
matriz_raizes = np.sqrt(matriz)

# Mostrar a nova matriz
print("Nova matriz com raízes quadradas dos elementos da matriz original:")
print(matriz_raizes)

# Realizar a divisão elemento a elemento da matriz original pela nova matriz
resultado_divisao = matriz / matriz_raizes

# Mostrar o resultado da divisão
print("\nResultado da divisão elemento a elemento da matriz original pela nova matriz:")
print(resultado_divisao)


Nova matriz com raízes quadradas dos elementos da matriz original:
[[7.74596669 7.93725393 8.42614977 ... 8.66025404 6.55743852 7.81024968]
 [3.46410162 4.         9.64365076 ... 3.16227766 7.54983444 5.19615242]
 [0.         9.43398113 8.1240384  ... 5.74456265 4.         9.32737905]
 ...
 [8.77496439 3.74165739 9.05538514 ... 4.69041576 5.74456265 4.69041576]
 [2.64575131 8.1240384  8.88819442 ... 7.54983444 8.60232527 6.63324958]
 [7.         6.         4.12310563 ... 7.61577311 8.71779789 3.60555128]]

Resultado da divisão elemento a elemento da matriz original pela nova matriz:
[[7.74596669 7.93725393 8.42614977 ... 8.66025404 6.55743852 7.81024968]
 [3.46410162 4.         9.64365076 ... 3.16227766 7.54983444 5.19615242]
 [       nan 9.43398113 8.1240384  ... 5.74456265 4.         9.32737905]
 ...
 [8.77496439 3.74165739 9.05538514 ... 4.69041576 5.74456265 4.69041576]
 [2.64575131 8.1240384  8.88819442 ... 7.54983444 8.60232527 6.63324958]
 [7.         6.         4.12310563 ... 7

<ipython-input-7-86351f157afc>:15: RuntimeWarning: invalid value encountered in divide
  resultado_divisao = matriz / matriz_raizes


Broadcast


In [8]:
#broadcasting
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # adiciona v a cada linha de x
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Exercicio 4

In [9]:
import numpy as np

# Carregar a matriz 50x50 com números inteiros randômicos entre 0 e 100 criada anteriormente
# Se você não tiver a matriz anteriormente criada, certifique-se de gerá-la primeiro
matriz_original = np.random.randint(0, 101, size=(50, 50))

# Criar uma cópia da matriz original
nova_matriz = np.copy(matriz_original)

# Identificar as colunas ímpares e tornar seus valores negativos, mantendo o mesmo módulo
for coluna in range(nova_matriz.shape[1]):
    if coluna % 2 != 0:  # Verificar se a coluna é ímpar
        nova_matriz[:, coluna] *= -1

# Mostrar a nova matriz com as colunas ímpares negativas, mas com o mesmo módulo dos valores da matriz original
print("Nova matriz com as colunas ímpares negativas (mesmo módulo):")
print(nova_matriz)


Nova matriz com as colunas ímpares negativas (mesmo módulo):
[[ 83 -67  24 ... -64  52 -43]
 [ 16 -47  28 ...   0  46 -29]
 [ 76 -18  90 ... -90  10 -78]
 ...
 [ 76 -37  26 ... -68  39 -87]
 [ 84 -27   1 ... -17  64 -64]
 [ 81 -52  37 ... -91  89 -90]]


Exercício 5

In [18]:
matriz_10linhas=nova_matriz.reshape(10,-1)
print(matriz_10linhas)

[[ 83 -67  24 ... -28  56 -89]
 [ 53 -62  79 ... -23   6 -86]
 [  1  -9  45 ... -37  61 -88]
 ...
 [ 16 -31  73 ... -12  75 -15]
 [ 37 -85  41 ...  -9  71 -42]
 [  8 -33  24 ... -91  89 -90]]


exercicio 6


In [29]:
x = matriz_original
print("x:",x)
soma_colunas = np.sum(x, axis=0)
indice_maior_coluna = np.argmax(soma_colunas)
soma_maior_coluna = soma_colunas[indice_maior_coluna]
print("Soma da maior coluna:", soma_maior_coluna)
valores_maiores50= x[x>=50]
print("valores maiores que 50", valores_maiores50)
print("maior valor da matriz toda:",x.max())
print("maior valor linha a linha da MATRIZ toda:",x.argmax(1))
# Encontrar o índice do maior valor na matriz
indice_maior_valor = np.argmax(matriz)

# Converter o índice em coordenadas de linha e coluna
linha, coluna = np.unravel_index(indice_maior_valor, matriz.shape)

print("Linha do maior valor:", linha)
print("Coluna do maior valor:", coluna)

x: [[83 67 24 ... 64 52 43]
 [16 47 28 ...  0 46 29]
 [76 18 90 ... 90 10 78]
 ...
 [76 37 26 ... 68 39 87]
 [84 27  1 ... 17 64 64]
 [81 52 37 ... 91 89 90]]
Soma da maior coluna: 2862
valores maiores que 50 [83 67 80 ... 91 89 90]
maior valor da matriz toda: 100
maior valor linha a linha da MATRIZ toda: [24 41 31  1  7  8  6  7  1 41 21 21 20 13 18 46 25 14 33  4 25 30  5 20
 31 14 17  2 47  0 13 33 37 31 33 45 46 26 16 19 18  9 36 30 30  6 38 21
 15 40]
Linha do maior valor: 0
Coluna do maior valor: 4


Concatenar linhas e colunas


In [30]:
a1 = np.array([[1,2,3],
               [4,5,6]])

a2 = np.array([[7,8,9],
               [10,11,12]])

o = np.hstack((a1, a2))

print(o)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
a1 = np.array([[1,2],
               [3,4],
               [5,6]])

a2 = np.array([[7,8],
               [9,10],
               [10,11]])

o = np.vstack((a1, a2))

print(o)

Exercicio 7

In [34]:
import numpy as np



# Calcular a média da matriz original
media = np.mean(matriz_original)
print(media)
# Criar uma cópia da matriz original
nova_matriz = np.copy(matriz_original)

# Atribuir zero a todos os valores maiores que a média
nova_matriz[nova_matriz > media] = 0

# Mostrar a nova matriz
print("Nova matriz onde os valores maiores que a média são iguais a zero:")
print(nova_matriz)


49.706
Nova matriz onde os valores maiores que a média são iguais a zero:
[[ 0  0 24 ...  0  0 43]
 [16 47 28 ...  0 46 29]
 [ 0 18  0 ...  0 10  0]
 ...
 [ 0 37 26 ...  0 39  0]
 [ 0 27  1 ... 17  0  0]
 [ 0  0 37 ...  0  0  0]]
